import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sales_app/componant/input/custom_text_field.dart';
import 'package:sizer/sizer.dart';

Widget getReactiveFormField({
  required FocusNode node,
  required TextEditingController controller,
  required String hintLabel,
  required void Function(String? val) onChanged,
  String? errorText,
  List<TextInputFormatter>? inputFormatters,
  required TextInputType inputType,
  FieldType? formType,
  Function? onVerifyButtonClick,
  bool? isVerified,
  bool? wantSuffix,
  bool? isDataValidated,
  Function? onTap,
  final Function? onEmailTap,
  Function? onForgotTap,
  Function? onPrefixTap,
  Function? onAddBtn,
  bool? isStarting,
  bool? isAdd,
  bool? isPhoto,
  bool? isDropdown,
  bool? isCalender,
  bool? isPass,
  bool? isPasswordOnly,
  bool? isFromVerifyPassword,
  bool? isReport,
  bool? isdown,
  bool? isMick,
  bool? isReadOnly,
  bool? fetchLocation,
  bool isFromCountry = false,
  bool isFromAddStory = false,
  bool isFromIntro = false,
  bool isEnable = true,
  bool isAddress = false,
  bool isSearch = false,
  bool isReview = false,
  bool isClose = false,
  bool isVerify = false,
  bool? isWhite,
  bool isGst = false,
  String? fromObsecureText,
  String? index,
  final Function? onSave,
  bool isReference = false,
  bool isOtp = false,
  bool isBorderSideEnable = true,
  bool isFromCaption = false,
  bool isRightIconShow = false,
  bool obscuretext = false,
  Function? obscureTextFunction,
  Function? onResendCode,
  Function? onVerifyClick,
  Function? onCountryClick,
  bool isUserPrefixShow = false,
  bool isCalendarIconShow = false,
  bool isCurrentPassIconShow = false,
  bool isNewPassIconShow = false,
  bool isConfirmPassIconShow = false,
  bool isEnableEditIcon = false,
  bool isFromDescription = false,
  bool isFromSocialIcon = false,
  String socialIcon = '',
  bool isCamera = false,
  bool isDate = false,
  Key? formFieldkey,
}) {
  return Container(
    margin: EdgeInsets.symmetric(
      vertical: Device.screenType == ScreenType.mobile ? 0.1.h : 0.2.h,
    ),
    child: CustomFormField(
      index: index,
      fromObsecureText: fromObsecureText,
      hintText: hintLabel,
      errorText: errorText,
      node: node,
      inputFormatters: inputFormatters,
      onChanged: onChanged,
      inputType: inputType,
      formType: formType,
      controller: controller,
      isCamera: isCamera,
      isDataValidated: isDate,
      isAddressField: isAddress,
      onVerifiyButtonClick: onVerifyButtonClick,
      isVerified: isVerified,
      isStarting: isStarting,
      isDropdown: isDropdown,
      isCalender: isCalender,
      isPassword: isPass,
      isAdd: isAdd,
      isdown: isdown,
      wantSuffix: wantSuffix,
      isReport: isReport,
      onTap: onTap,
      onPrefixTap: onPrefixTap,
      onAddBtn: onAddBtn,
      obsecuretext: obscuretext,
      isReferenceField: isReference,
      isFromAddStory: isFromAddStory,
      isEnable: isEnable,
      isReadOnly: isReadOnly,
      isWhite: isWhite,
      fetchLocation: fetchLocation,
      onSave: onSave,
      isGst: isGst,
      isBorderSideEnable: isBorderSideEnable,
      obscureFunction: obscureTextFunction,
      isMick: isMick,
      isClose: isClose,
    ),
  );
}
